### ISSUE TITLE
Union types are unsupported in structs

### ISSUE THREAD

**Issue by yaroslavnikiforov** [mkuczera/react-native-haptic-feedback#127]
`pod install` fails for version 2.3.0 (works with 2.2.0) with the following error:
```
Error: Union types are unsupported in structs
    at StructCollector.process (/Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/StructCollector.js:195:15)
    at getParamObjCType (/Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:261:23)
    at /Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:117:31
    at Array.forEach (<anonymous>)
    at serializeMethod (/Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:115:10)
    at serializeProperty (/Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/index.js:118:14)
    at Array.forEach (<anonymous>)
    at generate (/Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/index.js:133:10)
    at Object.generate (/Users/myuser/projects/myapp/node_modules/@react-native/codegen/lib/generators/RNCodegen.js:212:9)
    at Object.generateSpecFromInMemorySchema (/Users/myuser/projects/myapp/node_modules/react-native/scripts/codegen/generate-specs-cli-executor.js:78:22)
```

react-native: 0.74.3

**Comment by R3DST0RM** [comment]
Issue persists with react-native: 0.74.4

**Comment by Romick2005** [comment]
Looks like this [change](https://github.com/mkuczera/react-native-haptic-feedback/compare/v2.2.0...v2.3.0#diff-f3debe3a3241916f6ac7a6a5d0c5be2e217c25bcfbd9a72469c35368985db89d) cause the issue.

**Comment by dkumar-carfax** [comment]
Downgrading to `2.2.0` is a workaround for me for now.
